/// <reference types="next" />
/// <reference types="next/image-types/global" />
/// <reference types="react" />
/// <reference types="react-dom" />
/// <reference types="node" />

// NOTE: This file should not be edited.
// It is automatically generated by Next.js.
